### ISSUE TITLE
Update New Team Details

### ISSUE THREAD

**Issue by AdityaBirangal** [GDSCmitaoe/GDSCmitaoe.github.io#1]
- Update New Core Member Details
- Add New Team Member Details
- Move Old team to past team page

**Comment by niranjangirhe** [comment]
I'll do it

**Comment by niranjangirhe** [comment]
Let Yogesh dada do this as he have started with it

**Comment by yogesh0310** [comment]
Yeah I'm ready

**Comment by AdityaBirangal** [comment]
@yogesh0310 Any updates ?

**Comment by yogesh0310** [comment]
Changes pushed please check
