### ISSUE TITLE
Add Flutter Bootcamp Event

### ISSUE THREAD

**Issue by AdityaBirangal** [GDSCmitaoe/GDSCmitaoe.github.io#2]
- Add Flutter Bootcamp Event in 'Upcoming Events' Section
- Move 'Android Study Jam Session 1' to 'Past Event Section'

**Comment by niranjangirhe** [comment]
I'll do this

**Comment by niranjangirhe** [comment]
Please check the Pull request 7ed744f7307eed4e3187f81939c27abd22929222

**Comment by pratik-kale20** [comment]
Updated with the pull request https://github.com/GDSCmitaoe/GDSCmitaoe.github.io/commit/7ed744f7307eed4e3187f81939c27abd22929222
